name: ofup
channels:
- rdkit
- defaults
- openbabel
- acellera
dependencies:
- pip
- pip:
    - papermill
    - nteract-scrapbook
    - nglview
    - itables
    - joblib
    - matplotlib==3.0.2
- moleculekit
- rdkit=2019.03.3.0
- requests
- pandas=0.24.2
- numpy=1.16.4
- coverage
- openbabel=2.4.1
- jupyter
- htmd-pdb2pqr