name: ofup
channels:
- rdkit
- defaults
- openbabel
- acellera
dependencies:
- pip
- pip:
    - papermill
    - nteract-scrapbook
    - nglview
    - itables
    - joblib
- moleculekit
- rdkit
- requests
- pandas
- numpy
- coverage
- openbabel
- jupyter
